spring:
  application:
    name: apollo-adminservice
  profiles:
    active: github
  datasource:
    url: jdbc:mysql://ghb2ce-in-pd-data.mysql.rds.aliyuncs.com:3306/apolloconfigdb_pro?useSSL=false&characterEncoding=utf8
    username: bim5d_data_user
    password: A#Ff!o9QMWUT

ctrip:
  appid: 100003172
  
server:
  port: 8092
  
logging:
  file: /opt/logs/100003172/apollo-adminservice.log
