spring:
  application:
    name: apollo-configservice
#  profiles:
#    active: github
  datasource:
    url: jdbc:mysql://ohb2e-in-te-bim5d_platform.mysql.rds.aliyuncs.com:3306/apollo_config_db_uat?useSSL=false&characterEncoding=utf8
    username: bp_user
    password: TJIzDnPLf07rn#

ctrip:
  appid: 100003173
  
server:
  port: 8093
  
logging:
  file: /opt/logs/100003173/apollo-configservice.log
