spring:
  application:
    name: apollo-configservice
#  profiles:
#    active: github
  datasource:
    url: jdbc:mysql://ghb2f-in-te-data.mysql.rds.aliyuncs.com:3306/apolloconfigdb_uat?useSSL=false&characterEncoding=utf8
    username: bim5d_data_user
    password: kmJv@ULw#MKKQ

ctrip:
  appid: 100003173
  
server:
  port: 8093
  
logging:
  file: /opt/logs/100003173/apollo-configservice.log
