spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  datasource:
    url: jdbc:mysql://ghb2c-in-pd-business.mysql.rds.aliyuncs.com:3306/ApolloPortalDB?useSSL=false&characterEncoding=utf8
    username: bim5d_cm_admin
    password: AL6%Y4mofBXR&W!

server:
  port: 8093
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


