spring:
  application:
    name: apollo-portal
  profiles:
    active: auth
  datasource:
    url: jdbc:mysql://ohb2e-in-te-bim5d_platform.mysql.rds.aliyuncs.com:3306/apollo_portal?useSSL=false&characterEncoding=utf8
    username: bp_user
    password: TJIzDnPLf07rn#

server:
  port: 8095
  
logging:
  file: /opt/logs/100003175/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


