spring:
  application:
    name: apollo-portal
  profiles:
    active: auth
  datasource:
    url: jdbc:mysql://ghb2ce-in-pd-data.mysql.rds.aliyuncs.com:3306/apolloportaldb?useSSL=false&characterEncoding=utf8
    username: bim5d_data_user
    password: A#Ff!o9QMWUT

server:
  port: 8095
  
logging:
  file: /opt/logs/100003175/apollo-portal.log

endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


